### ISSUE TITLE
mvn compile build failure InterfaceCompileFailed

### ISSUE THREAD

**Issue by rCourtieux** [scapegoat-scala/scapegoat#770]
Hello, 

I have some difficulties to use scapegoat.
When i do mvn compile i get : 

[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:4.5.6:compile (default) on project standard-part: Execution default of goal net.alchim31.maven:scala-maven-plugin:4.5.6:compile failed: Compilation failed: **InterfaceCompileFailed** -> [Help 1]

I can see the scapegoat report in target but the compilation fail.

My configuration : 

              <plugin>
                <groupId>net.alchim31.maven</groupId>
                <artifactId>scala-maven-plugin</artifactId>
                <configuration>
                    <args>
                        <arg>-P:scapegoat:dataDir:./XXX/target/scapegoat</arg>
                    </args>
                    <compilerPlugins>
                        <compilerPlugin>
                            <groupId>com.sksamuel.scapegoat</groupId>
                            <artifactId>scalac-scapegoat-plugin_2.11.12</artifactId>
                            <version>1.4.17</version>
                        </compilerPlugin>
                    </compilerPlugins>
                </configuration>
              </plugin>

        <dependency>
            <groupId>com.sksamuel.scapegoat</groupId>
            <artifactId>scalac-scapegoat-plugin_2.11.12</artifactId>
            <version>1.4.17</version>
            <scope>provided</scope>
        </dependency>

JDK : corretto-1.8.0_382
SDK : 2.11.12
MVN : 3.9.2

Any ideas ? Thanks :)

**Comment by saeltz** [comment]
Sorry, no clue. I've never used Scala with Maven and haven't worked with Scala 2.11 and JDK 8 in a very long time.
Do you have a minimal project that reproduces the issue?

**Comment by mccartney** [comment]
I have no idea either.

But Googling led me to this: https://stackoverflow.com/questions/31851733/scala-compiliation-error-with-intellij
After reading that, I'd try running this all outside of IntelliJ - where your control of the execution environment (actual versions) is simpler.

**Comment by rCourtieux** [comment]
Hi, 

Yes i'm on Intellij, and i tried everything on your link without success.
I have found that : <arg>-P:scapegoat:overrideLevels:all=Warning</arg> don't break the maven build.
The counterpart is every issues are now warnings.

Do you have an option to not fail maven build on error issues ?

Thanks !
